extention_app_pairs = [
	'.txt', 'C:/windows/system32/notepad.exe',
	'.v', 'C:/Users/PACHECON/Apps/vscodium/VSCodium.exe',
	'.py', 'C:/Users/PACHECON/Apps/vscodium/VSCodium.exe',
	'', 'C:/windows/system32/notepad.exe',
	'.exe', '',
	'else', 'start " "',
]

favorite_folders = [
	'C:/Users/PACHECON/_cv',
	'C:/Users/PACHECON/Apps',
	'C:/Users/PACHECON/godot',
	'C:/Users/PACHECON/v',
	'C:/Users/PACHECON/_cv/file_manager'
]

start_path = 'C:/Users/PACHECON/_cv'
bg_color = [20, 10, 10]
folder_highlight = [163, 81, 181]
folder_font = [166, 202, 255]
choice_highlight = [63, 81, 181]
file_highlight = [63, 124, 181]
fav_highlight = [145, 45, 45]
search_highlight = [165, 25, 25]
keybinds = [['g', 'lazygit'], ['i', '"C:/Users/PACHECON/Apps/vscodium/VSCodium.exe" .'], ['s', 'sort /+15 /r prof.txt /o prof.txt']]